# See the documentation for more information:
# https://packit.dev/docs/configuration/

specfile_path: koji-fedoramessaging.spec

issue_repository: https://github.com/fedora-infra/koji-fedoramessaging

# name in upstream package repository or registry (e.g. in PyPI)
upstream_package_name: koji-fedoramessaging
# downstream (Fedora) RPM package name
downstream_package_name: koji-fedoramessaging

srpm_build_deps:
  - rpm-build

actions:
  create-archive:
    - "sh -c 'git archive -o koji-fedoramessaging-${PACKIT_PROJECT_VERSION}.tar.gz --prefix koji-fedoramessaging-${PACKIT_PROJECT_VERSION}/ HEAD'"
    - "sh -c 'echo koji-fedoramessaging-${PACKIT_PROJECT_VERSION}.tar.gz'"
  get-current-version:
    - "rpmspec -q --qf '%{V}' koji-fedoramessaging.spec"

targets:
  - fedora-latest-stable

jobs:

  # upon PRs, perform COPR builds
  - job: copr_build
    trigger: pull_request

  # upon releases, perform COPR builds
  - job: copr_build
    trigger: release
