# SPDX-FileCopyrightText: Contributors to the Fedora Project
#
# SPDX-License-Identifier: MIT

[tool.black]
line-length = 100

[tool.ruff]
select = ["E", "F", "W", "I", "UP", "S", "B", "RUF"]
line-length = 100
target-version = "py310"
ignore = ["RUF010", "UP038"]

[tool.ruff.per-file-ignores]
"tests/*" = ["S101"]

[tool.coverage.run]
branch = true
# source = ["koji_fedoramessaging"]

[tool.coverage.paths]
source = ["koji-fedoramessaging"]

[tool.coverage.report]
# fail_under = 100
exclude_lines = ["pragma: no cover", "if __name__ == .__main__.:"]
omit = ["tests/*"]
